GAM updates
timehop/nimbus-ios-sample pull request #4
Opened 2022-04-11 21:02 UTC by inderdhir

2022-04-11 21:11 UTC, victor-takai requested changes

2022-04-11 21:11 UTC, victor-takai commented on nimbus-ios-sample/Mediation Platforms/MediationViewController.swift
> +                showCustomAlert("google_banner_id")
Since all google keys were replaced with `google_placement_id` when we need to replace this `google_banner_id` (and the other ones below)

2022-04-11 21:15 UTC, brugg approved these changes

2022-04-12 15:24 UTC, victor-takai approved these changes

2022-04-12 15:48 UTC, merged